### ISSUE TITLE
Init issue

### ISSUE THREAD

**Issue by y2k-ss** [Nazin311/codefox#2]
@Nazin311 
Please find below the feedback and do the needful.
1. unable to revert back to index.html - change file name from "doc.html" to "index.html"
2. unable to revert back to thanks.html - change file name from "thank.html" to "thanks.html"
3. enable sticky session using cookies, if possible.

![file_html1](https://github.com/user-attachments/assets/7e8b0833-a160-4bad-a403-c99a9522a5e3)
![file_html2](https://github.com/user-attachments/assets/e019052e-ba0d-4ce1-849d-5a034ab6d0cd)

**Comment by Nazin311** [comment]
i have uploaded the files but i don't why it's showing as error
