### ISSUE TITLE
Corrective responsiveness

### ISSUE THREAD

**Issue by y2k-ss** [Nazin311/codefox#3]
@Nazin311 
Correct the CSS response for the pages - adapt to mobile devices.

![file_css2](https://github.com/user-attachments/assets/9f4505f0-f483-4814-8bf7-3d5760b85cb0)
![file_css3](https://github.com/user-attachments/assets/61c006e1-a1d6-4e02-87a0-32ae060e5e85)
![file_css1](https://github.com/user-attachments/assets/261d004d-380a-47c9-aaa5-bcd18a80959f)

**Comment by Nazin311** [comment]
I will correct it

**Comment by Nazin311** [comment]
I have uploaded the file .Now you can check it.

**Comment by y2k-ss** [comment]
Updates has been verified. Kindly proceed with the issue closure. Thanks for your support.

**Comment by Nazin311** [comment]
Done
